sudo: required
services:
    - docker

before_install:
    - docker build -t justawalker/docker-react -f Dockerfile.dev .

script:
    - docker run  justawalker/docker-react npm run test -- --coverage